### PR TITLE
FB tc support and filtering

### PR DESCRIPTION
**Pull request by turtledreams**
min api level to 21
target to 34
removed some calls for the api levels lower than 21
added tc:1 param to feedbak widget calls
added filter to select which links from a webview can be opened in a browser

only tc tested 
this just the prototype of what is wanted

### CODE REVIEW

**Review by arifBurakDemiray — APPROVED** [review]
why we are upgrading min sdk? is not it a big change?

**Comment by turtledreams** [comment]
please make this pr confirm to the android sdk structure and test it @arifBurakDemiray 
also check this out https://apilevels.com/
if there are other grander changes necessary please separate those to a different pr

**Review by arifBurakDemiray — APPROVED** [review]

**Review by AliRKat — APPROVED** [review]
Great work as always 🚀 
Out of curiosity; do we keep the lines that are commented out purposely in there? If we do, what is the reason I wondered.

**Comment by ArtursKadikis** [comment]
@turtledreams last you noted was that this is a prototype. Let me know once you feel this is ready

**Comment by turtledreams** [comment]
ready

**Pull request merged**
